window.dummyData = {
    booth1: {
        company: 'Puppy Face',
        information: 'Lorem ipsum dolor siquet est.',
        personell: ['Jonny', 'Jill'],
        boothNumber: 101,
        logo: 'PuppyFace.JPG',
        coordinatesLeftX: 20,
        coordinatesRightX: 60,
        coordinatesTopY: 30,
        coordinatesBottomY: 70,
        boothWidth: 40,
        boothHeight: 40,
        isAvailable: false
    },
    booth2: {
        company: 'SavingsLED',
        information: 'The quick brown fox jumped over the lazy dog.',
        personell: ['Snape', 'Harry'],
        boothNumber: 102,
        logo: 'SavingsLED.png',
        coordinatesLeftX: 70,
        coordinatesRightX: 110,
        coordinatesTopY: 30,
        coordinatesBottomY: 70,
        boothWidth: 40,
        boothHeight: 40,
        isAvailable: false
    },
    booth3: {
        company: 'Swirly',
        information: 'Witches cauldron brews mysterious frog and snail parts.',
        personell: ['Bertha'],
        boothNumber: 103,
        logo: 'Swirly.gif',
        coordinatesLeftX: 20,
        coordinatesRightX: 60,
        coordinatesTopY: 80,
        coordinatesBottomY: 120,
        boothWidth: 40,
        boothHeight: 40,
        isAvailable: false
    },
    booth4: {
        company: '',
        information: '',
        personell: [],
        boothNumber: 104,
        logo: '',
        coordinatesLeftX: 70,
        coordinatesRightX: 110,
        coordinatesTopY: 80,
        coordinatesBottomY: 120,
        boothWidth: 40,
        boothHeight: 40,
        isAvailable: true
    },
    booth5: {
        company: 'Vanguard',
        information: 'The ants go marching one by one hurrah, hurrahh.',
        personell: ['Nancy', 'Dennis', 'William'],
        boothNumber: 105,
        logo: 'Vanguard.jpg',
        coordinatesLeftX: 10,
        coordinatesRightX: 60,
        coordinatesTopY: 130,
        coordinatesBottomY: 200,
        boothWidth: 50,
        boothHeight: 70,
        isAvailable: false
    },
    booth6: {
        company: '',
        information: '',
        personell: [],
        boothNumber: 106,
        logo: '',
        coordinatesLeftX: 70,
        coordinatesRightX: 120,
        coordinatesTopY: 130,
        coordinatesBottomY: 200,
        boothWidth: 40,
        boothHeight: 40,
        isAvailable: true
    }
};